[features]
seeds = false
skip-lint = false
[programs.devnet]
pump_forking_meteora_sc = "2kKiLBYRzc7emXPHTmVzU9aPMAJ8oZ1m2wUWRno7Lfgq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/sammy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
